import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.database import SessionLocal
from app.models.topic import Topic, Section, Entry

def seed():
    db = SessionLocal()

    data = [
        {
            "title": "Otning 5 ta turlanishi",
            "sections": [
                {
                    "title": "I turlanish",
                    "image_url": None,
                    "entries": [
                        {"latin": "ala, ae, f", "uzbek": "qanot"},
                        {"latin": "vena, ae, f", "uzbek": "vena, qon tomiri"},
                        {"latin": "aorta, ae, f", "uzbek": "shox tomir"},
                        {"latin": "vertebra, ae, f", "uzbek": "umurtqa"},
                        {"latin": "arteria, ae, f", "uzbek": "arteriya, qon tomiri"},
                        {"latin": "patella, ae, f", "uzbek": "tizza qopqog'i"},
                        {"latin": "concha, ae, f", "uzbek": "chig'anoq"},
                        {"latin": "sutura, ae, f", "uzbek": "chok"},
                        {"latin": "costa, ae, f", "uzbek": "qovurg'a"},
                        {"latin": "tuba, ae, f", "uzbek": "nay, truba"},
                        {"latin": "crista, ae, f", "uzbek": "qirra"},
                        {"latin": "bucca, ae, f", "uzbek": "lunj"},
                        {"latin": "lamina, ae, f", "uzbek": "plastinka"},
                        {"latin": "gingiva, ae, f", "uzbek": "milk"},
                        {"latin": "lingua, ae, f", "uzbek": "til"},
                        {"latin": "lingula, ae, f", "uzbek": "tilcha"},
                        {"latin": "orbita, ae, f", "uzbek": "ko'z kosasi"},
                        {"latin": "papilla, ae, f", "uzbek": "so'rg'ich"},
                        {"latin": "protuberantia, ae, f", "uzbek": "bo'rtma"},
                        {"latin": "corona, ae, f", "uzbek": "toj"},
                        {"latin": "aqua, ae, f", "uzbek": "suv"},
                        {"latin": "scapula, ae, f", "uzbek": "kurak"},
                        {"latin": "bursa, ae, f", "uzbek": "xalta"},
                        {"latin": "valvula, ae, f", "uzbek": "qopqoq"},
                        {"latin": "pleura, ae, f", "uzbek": "parda, plevra"},
                        {"latin": "maxilla, ae, f", "uzbek": "yuqori jag'"},
                        {"latin": "mandibula, ae, f", "uzbek": "pastki jag'"},
                        {"latin": "tibia, ae, f", "uzbek": "katta boldir suyagi"},
                        {"latin": "fibula, ae, f", "uzbek": "kichik boldir suyagi"},
                        {"latin": "spina, ae, f", "uzbek": "qirra"},
                        {"latin": "pulpa, ae, f", "uzbek": "tish pulpasi, eti"},
                        {"latin": "incisura, ae, f", "uzbek": "o'yma"},
                        {"latin": "columna, ae, f", "uzbek": "pog'ona"},
                        {"latin": "membrana, ae, f", "uzbek": "parda"},
                        {"latin": "lacrima, ae, f", "uzbek": "ko'z yoshi"},
                        {"latin": "glandula, ae, f", "uzbek": "bez"},
                        {"latin": "ampulla, ae, f", "uzbek": "ampula"},
                        {"latin": "porta, ae, f", "uzbek": "darvoza"},
                        {"latin": "vita, ae, f", "uzbek": "hayot"},
                        {"latin": "cella, ae, f", "uzbek": "hujayra"},
                        {"latin": "urina, ae, f", "uzbek": "siydik"},
                        {"latin": "tunica, ae, f", "uzbek": "qobiq, parda"},
                        {"latin": "lamella, ae, f", "uzbek": "plastinka"},
                        {"latin": "plica, ae, f", "uzbek": "qatlam"},
                        {"latin": "vesica, ae, f", "uzbek": "pufak"},
                        {"latin": "vagina, ae, f", "uzbek": "qin"},
                        {"latin": "linea, ae, f", "uzbek": "chiziq"},
                        {"latin": "fibra, ae, f", "uzbek": "tola"},
                        {"latin": "mucosa, ae, f", "uzbek": "shilliq"},
                        {"latin": "flexura, ae, f", "uzbek": "egilish"},
                        {"latin": "conjunctiva, ae, f", "uzbek": "ko'z shilliq pardasi"},
                        {"latin": "urethra, ae, f", "uzbek": "siydik chiqarish kanali"},
                        {"latin": "fissura, ae, f", "uzbek": "yoriq, tirqish"},
                        {"latin": "fovea, ae, f", "uzbek": "chuqurcha"},
                    ],
                },
                {
                    "title": "II turlanish",
                    "image_url": None,
                    "entries": [
                        {"latin": "angulus, i, m", "uzbek": "burchak"},
                        {"latin": "digitus, i, m", "uzbek": "barmoq"},
                        {"latin": "tuberculum, i, n", "uzbek": "do'mboqcha"},
                        {"latin": "acromion, i, n", "uzbek": "kurak o'simtasi"},
                        {"latin": "brachium, i, n", "uzbek": "yelka"},
                        {"latin": "humerus, i, m", "uzbek": "yelka suyagi"},
                        {"latin": "cavum, i, n", "uzbek": "bo'shliq"},
                        {"latin": "manubrium, i, n", "uzbek": "tutqich, dasta"},
                        {"latin": "cranium, i, n", "uzbek": "kalla, kalla suyagi"},
                        {"latin": "radius, i, m", "uzbek": "bilak suyagi"},
                        {"latin": "ligamentum, i, n", "uzbek": "boylam"},
                        {"latin": "sternum, i, n", "uzbek": "to'sh"},
                        {"latin": "musculus, i, m", "uzbek": "mushak"},
                        {"latin": "alveolus, i, m", "uzbek": "alveola, yacheyka"},
                        {"latin": "septum, i, n", "uzbek": "to'siq"},
                        {"latin": "frenulum, i, n", "uzbek": "yugan"},
                        {"latin": "sulcus, i, m", "uzbek": "egat"},
                        {"latin": "tympanum, i, n", "uzbek": "nog'ora parda"},
                        {"latin": "labium, i, n", "uzbek": "lab"},
                        {"latin": "calcaneus, i, m", "uzbek": "tovon suyagi"},
                        {"latin": "oculus, i, m", "uzbek": "ko'z"},
                        {"latin": "bronchus, i, m", "uzbek": "bronx"},
                        {"latin": "nodus, i, m", "uzbek": "tugun"},
                        {"latin": "lobus, i, m", "uzbek": "bo'lak"},
                        {"latin": "nasus, i, m", "uzbek": "burun"},
                        {"latin": "dentinum, i, n", "uzbek": "dentin"},
                        {"latin": "enamelum, i, n", "uzbek": "emal"},
                        {"latin": "caninus, i, m", "uzbek": "qoziq tish"},
                        {"latin": "incisivus, i, m", "uzbek": "kesuvchi tish"},
                        {"latin": "palatum, i, n", "uzbek": "tanglay"},
                        {"latin": "cerebellum, i, n", "uzbek": "miyacha"},
                        {"latin": "cerebrum, i, n", "uzbek": "bosh miya"},
                        {"latin": "encephalon, i, n", "uzbek": "bosh miya"},
                        {"latin": "nervus, i, m", "uzbek": "asab"},
                        {"latin": "ganglion, i, n", "uzbek": "nerv tuguni"},
                        {"latin": "ostium, i, n", "uzbek": "teshik"},
                        {"latin": "collum, i, n", "uzbek": "bo'yin"},
                        {"latin": "dorsum, i, n", "uzbek": "orqa"},
                        {"latin": "decoctum, i, n", "uzbek": "qaynatma"},
                        {"latin": "globulus, i, m", "uzbek": "sharcha"},
                        {"latin": "aegrotus, i, m", "uzbek": "bemor"},
                        {"latin": "ilium, i, n", "uzbek": "yonbosh suyagi"},
                        {"latin": "organum, i, n", "uzbek": "a'zo"},
                        {"latin": "nitrogenium, i, n", "uzbek": "azot"},
                        {"latin": "aluminium, i, n", "uzbek": "aluminiy"},
                        {"latin": "ammonium, i, n", "uzbek": "ammoniy"},
                        {"latin": "medicamentum, i, n", "uzbek": "dori"},
                        {"latin": "sacrum, i, n", "uzbek": "dumg'aza"},
                        {"latin": "abdomen, inis, n", "uzbek": "qorin"},
                        {"latin": "intestinum, i, n", "uzbek": "ichak"},
                        {"latin": "centrum, i, n", "uzbek": "markaz"},
                        {"latin": "bulbus, i, m", "uzbek": "piyozcha"},
                        {"latin": "truncus, i, m", "uzbek": "tana, poya, gavda"},
                        {"latin": "rectum, i, n", "uzbek": "to'g'ri ichak"},
                        {"latin": "reticulum, i, n", "uzbek": "to'r"},
                        {"latin": "saccharum, i, n", "uzbek": "shakar"},
                        {"latin": "vitaminium, i, n", "uzbek": "vitamin"},
                        {"latin": "colon, i, n", "uzbek": "pardali ichak"},
                        {"latin": "ventriculus, i, m", "uzbek": "oshqozon"},
                        {"latin": "duodenum, i, n", "uzbek": "12 barmoq ichak"},
                        {"latin": "anus, i, m", "uzbek": "orqa kanal"},
                        {"latin": "crassum, i, n", "uzbek": "yo'g'on ichak"},
                        {"latin": "peritonaeum, i, n", "uzbek": "qorin bo'shlig'i"},
                        {"latin": "fundus, i, m", "uzbek": "tub"},
                        {"latin": "oesophagus, i, m", "uzbek": "qizilo'ngach"},
                        {"latin": "jejunum, i, n", "uzbek": "ingichka ichak"},
                        {"latin": "ovarium, i, n", "uzbek": "tuxumdon"},
                        {"latin": "uterus, i, m", "uzbek": "bachadon"},
                        {"latin": "caecum, i, n", "uzbek": "ko'richak"},
                        {"latin": "gyrus, i, m", "uzbek": "burma"},
                        {"latin": "folium, i, n", "uzbek": "barg"},
                    ],
                },
                {
                    "title": "III turlanish",
                    "image_url": None,
                    "entries": [
                        {"latin": "flos, floris, m", "uzbek": "gul"},
                        {"latin": "corpus, oris, n", "uzbek": "tana"},
                        {"latin": "foramen, inis, n", "uzbek": "teshik"},
                        {"latin": "os, ossis, n", "uzbek": "suyak"},
                        {"latin": "crus, cruris, n", "uzbek": "oyoq, oyoqcha"},
                        {"latin": "pulmo, onis, m", "uzbek": "o'pka"},
                        {"latin": "caput, itis, n", "uzbek": "bosh, boshcha"},
                        {"latin": "cartilago, onis, f", "uzbek": "tog'ay"},
                        {"latin": "basis, is, f", "uzbek": "asos"},
                    ],
                },
                {
                    "title": "IV turlanish",
                    "image_url": None,
                    "entries": [
                        {"latin": "ductus, us, m", "uzbek": "oqim"},
                        {"latin": "genu, us, n", "uzbek": "tizza"},
                        {"latin": "arcus, us, m", "uzbek": "yoy, ravoq"},
                        {"latin": "processus, us, m", "uzbek": "o'simta"},
                        {"latin": "cornu, us, n", "uzbek": "shox"},
                        {"latin": "sinus, us, n", "uzbek": "bo'shliq"},
                        {"latin": "plexus, us, m", "uzbek": "chigal"},
                        {"latin": "textus, us, m", "uzbek": "to'qima"},
                        {"latin": "manus, us, n", "uzbek": "qo'l"},
                        {"latin": "pulsus, us, m", "uzbek": "tomir urishi"},
                    ],
                },
                {
                    "title": "V turlanish",
                    "image_url": None,
                    "entries": [
                        {"latin": "facies, ei, f", "uzbek": "yuza"},
                        {"latin": "superficies, ei, f", "uzbek": "yuqori yuza"},
                        {"latin": "dies, ei, f", "uzbek": "kun"},
                        {"latin": "caries, ei, f", "uzbek": "kariyes"},
                        {"latin": "rabies, ei, f", "uzbek": "quturish"},
                        {"latin": "scabies, ei, f", "uzbek": "qichima"},
                        {"latin": "species, ei, f", "uzbek": "yig'ma"},
                    ],
                },
            ],
        },
        {
            "title": "Otning 3 turlanishi",
            "sections": [
                {
                    "title": "Mujskoy rod",
                    "image_url": None,
                    "entries": [
                        {"latin": "apex, icis, m", "uzbek": "uchi (burun, til)"},
                        {"latin": "cortex, icis, m", "uzbek": "po'stloq, qobiq"},
                        {"latin": "flos, oris, m", "uzbek": "gul"},
                        {"latin": "homo, inis, m", "uzbek": "odam"},
                        {"latin": "liquor, oris, m", "uzbek": "orqa miya suyuqligi"},
                        {"latin": "paries, etis, m", "uzbek": "devor"},
                        {"latin": "pulmo, onis, m", "uzbek": "o'pka"},
                        {"latin": "venter, ntris, m", "uzbek": "qorincha, qorin"},
                        {"latin": "vertex, icis, m", "uzbek": "cho'qqi"},
                        {"latin": "vomer, eris, m", "uzbek": "dimog'"},
                        {"latin": "index, icis, m", "uzbek": "ko'rsatkich barmoq"},
                        {"latin": "humor, oris, m", "uzbek": "namlik, tananing suyuq qismi"},
                        {"latin": "pes, pedis, m", "uzbek": "oyoq"},
                        {"latin": "pollex, icis, m", "uzbek": "bosh barmoq"},
                        {"latin": "stapes, edis, m", "uzbek": "uzangi"},
                        {"latin": "ureter, eris, m", "uzbek": "siydik yo'li"},
                        {"latin": "dens, dentis, m", "uzbek": "tish"},
                        {"latin": "axis, is, m", "uzbek": "o'q, ikkinchi bo'yin umurtqasi"},
                        {"latin": "canalis, is, m", "uzbek": "kanal"},
                        {"latin": "margo, inis, m", "uzbek": "chet"},
                        {"latin": "sanguis, inis, m", "uzbek": "qon"},
                        {"latin": "tendo, inis, m", "uzbek": "pay"},
                        {"latin": "coccyx, ygis, m", "uzbek": "dum"},
                        {"latin": "fornix, icis, m", "uzbek": "gumbaz"},
                        {"latin": "larynx, ngis, m", "uzbek": "hiqildoq"},
                        {"latin": "pharynx, ngis, m", "uzbek": "halqum"},
                        {"latin": "thorax, acis, m", "uzbek": "ko'krak qafasi"},
                    ],
                },
                {
                    "title": "Istisno so'zlar",
                    "image_url": None,
                    "entries": [
                        {"latin": "os, oris, n", "uzbek": "og'iz"},
                        {"latin": "tuber, eris, n", "uzbek": "do'mboq"},
                        {"latin": "os, ossis, n", "uzbek": "suyak"},
                        {"latin": "gaster, tris, f", "uzbek": "me'da, oshqozon"},
                        {"latin": "cor, cordis, n", "uzbek": "yurak"},
                        {"latin": "mater, matris, f", "uzbek": "ona, miya pardasi"},
                        {"latin": "dura mater", "uzbek": "miyaning qattiq pardasi"},
                        {"latin": "pia mater", "uzbek": "miyaning yumshoq pardasi"},
                    ],
                },
                {
                    "title": "Jenskiy rod",
                    "image_url": None,
                    "entries": [
                        {"latin": "appendix, icis, f", "uzbek": "o'simta"},
                        {"latin": "carotis, tidis, f", "uzbek": "uyqu arteriyasi"},
                        {"latin": "articulatio, onis, f", "uzbek": "bo'g'im"},
                        {"latin": "auris, is, f", "uzbek": "quloq"},
                        {"latin": "basis, is, f", "uzbek": "asos"},
                        {"latin": "cavitas, atis, f", "uzbek": "bo'shliq"},
                        {"latin": "cervix, icis, f", "uzbek": "bo'yin, bo'yincha"},
                        {"latin": "cutis, is, f", "uzbek": "teri"},
                        {"latin": "frons, frontis, f", "uzbek": "peshona"},
                        {"latin": "gl. parotis, tidis, f", "uzbek": "quloq oldi bezi"},
                        {"latin": "meninx, ngis, f", "uzbek": "miya pardasi"},
                        {"latin": "pars, partis, f", "uzbek": "qism"},
                        {"latin": "radix, icis, f", "uzbek": "ildiz"},
                        {"latin": "pelvis, is, f", "uzbek": "tos, chanoq"},
                        {"latin": "pelvis renalis", "uzbek": "buyrak jomchasi"},
                        {"latin": "pyramis, idis, f", "uzbek": "piramida"},
                        {"latin": "regio, onis, f", "uzbek": "soha"},
                        {"latin": "synchondrosis, is, f", "uzbek": "sinxondroz"},
                        {"latin": "symphysis, is, f", "uzbek": "birikish"},
                        {"latin": "tuberositas, atis, f", "uzbek": "g'adir-budirlik"},
                        {"latin": "bilis, is, f", "uzbek": "o't, safro"},
                        {"latin": "extremitas, atis, f", "uzbek": "qo'l-oyoq uchi"},
                        {"latin": "impressio, onis, f", "uzbek": "botiqlik"},
                        {"latin": "iris, idis, f", "uzbek": "ko'zning kamalak pardasi"},
                        {"latin": "lens, lentis, f", "uzbek": "ko'z gavhari"},
                        {"latin": "phalanx, ngis, f", "uzbek": "panja suyagi"},
                        {"latin": "pubes, is, f", "uzbek": "qov, qov suyagi"},
                    ],
                },
                {
                    "title": "Sredniy rod",
                    "image_url": None,
                    "entries": [
                        {"latin": "abdomen, inis, n", "uzbek": "qorin"},
                        {"latin": "caput, itis, n", "uzbek": "bosh"},
                        {"latin": "corpus, oris, n", "uzbek": "tana"},
                        {"latin": "diaphragma, atis, n", "uzbek": "diafragma"},
                        {"latin": "foramen, inis, n", "uzbek": "teshik"},
                        {"latin": "neoplasma, atis, n", "uzbek": "neoplazma"},
                        {"latin": "hepar, atis, n", "uzbek": "jigar"},
                        {"latin": "occiput, itis, n", "uzbek": "ensa"},
                        {"latin": "pectus, oris, n", "uzbek": "ko'krak"},
                        {"latin": "stroma, atis, n", "uzbek": "tayanch"},
                        {"latin": "tempus, oris, n", "uzbek": "chakka"},
                        {"latin": "tegmen, inis, n", "uzbek": "qopqoq"},
                        {"latin": "zygoma, atis, n", "uzbek": "yonoq"},
                        {"latin": "viscus, eris, n", "uzbek": "ichki organlar"},
                        {"latin": "chiasma, atis, n", "uzbek": "kesishma"},
                        {"latin": "femur, oris, n", "uzbek": "son"},
                        {"latin": "glomus, eris, n", "uzbek": "to'pcha"},
                        {"latin": "systema, atis, n", "uzbek": "tizim"},
                        {"latin": "coma, atis, n", "uzbek": "koma"},
                        {"latin": "crus, cruris, n", "uzbek": "oyoqcha"},
                        {"latin": "calcar, aris, n", "uzbek": "sal"},
                        {"latin": "sal, salis, n", "uzbek": "tuz"},
                        {"latin": "animal, alis, n", "uzbek": "hayvon"},
                        {"latin": "rete, retis, n", "uzbek": "to'r"},
                        {"latin": "ren, renis, m", "uzbek": "buyrak"},
                        {"latin": "lien, lienis, m", "uzbek": "taloq"},
                    ],
                },
            ],
        },
        {
            "title": "Sifatning 1 va 2 guruhlari",
            "sections": [
                {
                    "title": "I guruh sifatlari",
                    "image_url": None,
                    "entries": [
                        {"latin": "cavus, a, um", "uzbek": "bo'sh, kovak"},
                        {"latin": "cutaneus, a, um", "uzbek": "teriga oid"},
                        {"latin": "ischiadicus, a, um", "uzbek": "quymichga oid"},
                        {"latin": "latus, a, um", "uzbek": "keng"},
                        {"latin": "profundus, a, um", "uzbek": "chuqur"},
                        {"latin": "mastoideus, a, um", "uzbek": "so'rg'ichsimon"},
                        {"latin": "hyoideus, a, um", "uzbek": "til osti suyagiga oid"},
                        {"latin": "canninus, a, um", "uzbek": "katta oziq tishga oid"},
                        {"latin": "hypoglossus, a, um", "uzbek": "til osti nerviga oid"},
                        {"latin": "submucosus, a, um", "uzbek": "shilliq parda osti"},
                        {"latin": "geniohyoideus, a, um", "uzbek": "iyak-til osti"},
                        {"latin": "stylohyoideus, a, um", "uzbek": "til uchi osti"},
                        {"latin": "stylopharingeus, a, um", "uzbek": "halqum uchiga oid"},
                        {"latin": "infrahyoideus, a, um", "uzbek": "til osti"},
                        {"latin": "serotinus, a, um", "uzbek": "kechki, aql"},
                        {"latin": "palatinus, a, um", "uzbek": "tanglayga oid"},
                        {"latin": "albus, a, um", "uzbek": "oq"},
                        {"latin": "niger, gra, grum", "uzbek": "qora"},
                        {"latin": "flavus, a, um", "uzbek": "sariq"},
                        {"latin": "ruber, bra, brum", "uzbek": "qizil"},
                        {"latin": "longus, a, um", "uzbek": "uzun"},
                        {"latin": "brevis, e", "uzbek": "qisqa"},
                        {"latin": "magnus, a, um", "uzbek": "katta"},
                        {"latin": "parvus, a, um", "uzbek": "kichik"},
                        {"latin": "altus, a, um", "uzbek": "baland"},
                        {"latin": "durus, a, um", "uzbek": "qattiq"},
                        {"latin": "calidus, a, um", "uzbek": "issiq"},
                        {"latin": "frigidus, a, um", "uzbek": "sovuq"},
                        {"latin": "rectus, a, um", "uzbek": "to'g'ri"},
                        {"latin": "bonus, a, um", "uzbek": "yaxshi"},
                        {"latin": "malus, a, um", "uzbek": "yomon"},
                        {"latin": "purus, a, um", "uzbek": "toza"},
                        {"latin": "rotundus, a, um", "uzbek": "yumaloq"},
                        {"latin": "coeruleus, a, um", "uzbek": "ko'k"},
                        {"latin": "cinereus, a, um", "uzbek": "kul rang"},
                        {"latin": "laryngeus, a, um", "uzbek": "hiqildoqqa oid"},
                        {"latin": "pharyngeus, a, um", "uzbek": "halqumga oid"},
                        {"latin": "oesophageus, a, um", "uzbek": "qizilo'ngachga oid"},
                        {"latin": "amarus, a, um", "uzbek": "achchiq"},
                        {"latin": "acutus, a, um", "uzbek": "o'tkir"},
                        {"latin": "dexter, tra, trum", "uzbek": "o'ng"},
                        {"latin": "sinister, tra, trum", "uzbek": "chap"},
                        {"latin": "obliquus, a, um", "uzbek": "qiyshiq, egri"},
                        {"latin": "osseus, a, um", "uzbek": "suyakka oid"},
                        {"latin": "thoracicus, a, um", "uzbek": "ko'krakka oid"},
                        {"latin": "thyreoideus, a, um", "uzbek": "qalqonsimon"},
                        {"latin": "transversus, a, um", "uzbek": "ko'ndalang"},
                    ],
                },
                {
                    "title": "II guruh sifatlari",
                    "image_url": None,
                    "entries": [
                        {"latin": "auricularis, e", "uzbek": "quloqqa oid"},
                        {"latin": "lacrimalis, e", "uzbek": "ko'z yoshiga oid"},
                        {"latin": "dorsalis, e", "uzbek": "orqaga oid"},
                        {"latin": "lingualis, e", "uzbek": "tilga oid"},
                        {"latin": "facialis, e", "uzbek": "yuzaga oid"},
                        {"latin": "ventralis, e", "uzbek": "oldingi"},
                        {"latin": "superficialis, e", "uzbek": "yuzaki"},
                        {"latin": "proximalis, e", "uzbek": "tanaga yaqin"},
                        {"latin": "distalis, e", "uzbek": "tanadan uzoq"},
                        {"latin": "horizontalis, e", "uzbek": "gorizontal, eniga"},
                        {"latin": "lumbalis, e", "uzbek": "belga oid"},
                        {"latin": "nasalis, e", "uzbek": "burunga oid"},
                        {"latin": "temporalis, e", "uzbek": "chakkaga oid"},
                        {"latin": "occipitalis, e", "uzbek": "ensaga oid"},
                        {"latin": "maxillaris, e", "uzbek": "yuqori jag'ga oid"},
                        {"latin": "mandibularis, e", "uzbek": "pastki jag'ga oid"},
                        {"latin": "intestinalis, e", "uzbek": "ichakka oid"},
                        {"latin": "tenuis, e", "uzbek": "ingichka"},
                        {"latin": "simplex, icis", "uzbek": "oddiy"},
                        {"latin": "triceps, itis", "uzbek": "uch boshli"},
                        {"latin": "teres, es", "uzbek": "aylana"},
                        {"latin": "vaginalis, e", "uzbek": "qinga oid"},
                        {"latin": "biceps, itis", "uzbek": "ikki boshli"},
                        {"latin": "quadriceps, itis", "uzbek": "to'rt boshli"},
                        {"latin": "dentalis, e", "uzbek": "tishga oid"},
                        {"latin": "cranialis, e", "uzbek": "kallaga oid"},
                        {"latin": "mollis, e", "uzbek": "yumshoq"},
                        {"latin": "cardialis, e", "uzbek": "yurakka oid"},
                        {"latin": "pulmonalis, e", "uzbek": "o'pkaga oid"},
                        {"latin": "renalis, e", "uzbek": "buyrakka oid"},
                        {"latin": "abdominalis, e", "uzbek": "qoringa oid"},
                        {"latin": "brachialis, e", "uzbek": "yelkaga oid"},
                        {"latin": "humeralis, e", "uzbek": "yelka suyagiga oid"},
                        {"latin": "radialis, e", "uzbek": "bilakka oid"},
                        {"latin": "ulnaris, e", "uzbek": "tirsakka oid"},
                        {"latin": "alaris, e", "uzbek": "qanotga oid"},
                        {"latin": "buccalis, e", "uzbek": "lunjga oid"},
                        {"latin": "orbitalis, e", "uzbek": "ko'z kosasiga oid"},
                        {"latin": "mentalis, e", "uzbek": "iyakka oid"},
                        {"latin": "cerebralis, e", "uzbek": "miyaga oid"},
                        {"latin": "cervicalis, e", "uzbek": "bo'yinga tegishli"},
                        {"latin": "frontalis, e", "uzbek": "peshonaga oid"},
                    ],
                },
            ],
        },
        {
            "title": "Tish anatomiyasi va qavatlari",
            "sections": [
                {
                    "title": "Tish anatomiyasi va qavatlari",
                    "image_url": None,
                    "entries": [
                        {"latin": "dens", "uzbek": "tish"},
                        {"latin": "corona dentis", "uzbek": "tish toji"},
                        {"latin": "cervix dentis", "uzbek": "tish bo'yni"},
                        {"latin": "radix dentis", "uzbek": "tish ildizi"},
                        {"latin": "pulpa dentis", "uzbek": "tish pulpasi"},
                        {"latin": "dentinum", "uzbek": "dentin"},
                        {"latin": "enamelum", "uzbek": "emal"},
                        {"latin": "cementum", "uzbek": "sement qavati"},
                        {"latin": "apex radicis", "uzbek": "ildiz uchi"},
                        {"latin": "canalis radicis", "uzbek": "ildiz kanali"},
                        {"latin": "ligamentum periodontale", "uzbek": "periodont boylami"},
                        {"latin": "gingiva", "uzbek": "milk"},
                        {"latin": "nervus", "uzbek": "nerv"},
                    ],
                },
                {
                    "title": "Tish turlari",
                    "image_url": None,
                    "entries": [
                        {"latin": "dens incisivus", "uzbek": "kurak tish"},
                        {"latin": "dens caninus", "uzbek": "qoziq tish"},
                        {"latin": "dens premolaris", "uzbek": "kichik oziq tish"},
                        {"latin": "dens molaris", "uzbek": "katta oziq tish"},
                        {"latin": "dens deciduus", "uzbek": "sut tishi"},
                        {"latin": "dens permanens", "uzbek": "doimiy tish"},
                        {"latin": "dens serotinus", "uzbek": "kech chiqadigan tish, aql tish"},
                        {"latin": "arcus dentalis", "uzbek": "tish yoyi"},
                        {"latin": "dens molaris tertius", "uzbek": "uchinchi molyar tish, aql tish"},
                    ],
                },
            ],
        },
        {
            "title": "Og'iz bo'shlig'i",
            "sections": [
                {
                    "title": "Og'iz bo'shlig'i",
                    "image_url": None,
                    "entries": [
                        {"latin": "cavitas oris", "uzbek": "og'iz bo'shlig'i"},
                        {"latin": "gingiva", "uzbek": "milk"},
                        {"latin": "palatum", "uzbek": "tanglay"},
                        {"latin": "palatum durum", "uzbek": "qattiq tanglay"},
                        {"latin": "palatum molle", "uzbek": "yumshoq tanglay"},
                        {"latin": "lingua", "uzbek": "til"},
                        {"latin": "labium", "uzbek": "lab"},
                        {"latin": "labium superius", "uzbek": "yuqori lab"},
                        {"latin": "labium inferius", "uzbek": "pastki lab"},
                        {"latin": "bucca", "uzbek": "lunj"},
                        {"latin": "mandibula", "uzbek": "pastki jag'"},
                        {"latin": "maxilla", "uzbek": "yuqori jag'"},
                        {"latin": "articulatio temporomandibularis", "uzbek": "chakka-pastki jag' bo'g'imi"},
                        {"latin": "alveolus dentis", "uzbek": "tish katagi, alveolasi"},
                        {"latin": "uvula", "uzbek": "tilcha"},
                        {"latin": "tonsilla", "uzbek": "bodomcha bez"},
                    ],
                },
            ],
        },
        {
            "title": "Kalla suyagi",
            "sections": [
                {
                    "title": "Kalla suyaklari",
                    "image_url": None,
                    "entries": [
                        {"latin": "ossa cranii", "uzbek": "kalla suyaklari"},
                        {"latin": "neurocranium", "uzbek": "miya qismi kallasi"},
                        {"latin": "os frontale", "uzbek": "peshona suyagi"},
                        {"latin": "os parietale", "uzbek": "tepa suyagi"},
                        {"latin": "os temporale", "uzbek": "chakka suyagi"},
                        {"latin": "os occipitale", "uzbek": "ensa suyagi"},
                        {"latin": "os sphenoidale", "uzbek": "ponasimon suyagi"},
                        {"latin": "os ethmoidale", "uzbek": "g'alvirsimon suyagi"},
                        {"latin": "processus styloideus", "uzbek": "bigizsimon o'siq"},
                    ],
                },
                {
                    "title": "Yuz suyaklari",
                    "image_url": None,
                    "entries": [
                        {"latin": "ossa faciei", "uzbek": "yuz suyaklari"},
                        {"latin": "viscerocranium", "uzbek": "yuz qismi kallasi"},
                        {"latin": "maxilla", "uzbek": "yuqori jag' suyagi"},
                        {"latin": "mandibula", "uzbek": "pastki jag' suyagi"},
                        {"latin": "os zygomaticum", "uzbek": "yonoq suyagi"},
                        {"latin": "os nasale", "uzbek": "burun suyagi"},
                        {"latin": "os lacrimale", "uzbek": "ko'z yosh suyagi"},
                        {"latin": "os palatinum", "uzbek": "tanglay suyagi"},
                        {"latin": "concha nasalis inferior", "uzbek": "pastki burun chig'anog'i"},
                        {"latin": "vomer", "uzbek": "dimog' suyagi"},
                        {"latin": "os hyoideum", "uzbek": "til osti suyagi"},
                    ],
                },
                {
                    "title": "Kalla choklari",
                    "image_url": None,
                    "entries": [
                        {"latin": "sutura parietomastoidea", "uzbek": "tepa-so'rg'ichsimon chok"},
                        {"latin": "sutura occipitomastoidea", "uzbek": "ensa-so'rg'ichsimon chok"},
                        {"latin": "sutura temporozygomatica", "uzbek": "chakka-yonoq choki"},
                        {"latin": "sutura zygomaticomaxillaris", "uzbek": "yonoq-yuqori jag' choki"},
                        {"latin": "sutura sphenofrontalis", "uzbek": "ponasimon-peshona choki"},
                        {"latin": "sutura ethmoidolacrimalis", "uzbek": "g'alvirsimon-ko'z yosh choki"},
                        {"latin": "sutura coronalis", "uzbek": "tojsimon chok"},
                        {"latin": "sutura frontozygomatica", "uzbek": "peshona-yonoq choki"},
                        {"latin": "sutura sphenoparietalis", "uzbek": "ponasimon-tepa choki"},
                    ],
                },
            ],
        },
        {
            "title": "Yuz mushaklari",
            "sections": [
                {
                    "title": "Yuz mushaklari",
                    "image_url": None,
                    "entries": [
                        {"latin": "M. occipitofrontalis", "uzbek": "peshona-ensa mushagi"},
                        {"latin": "M. orbicularis oculi", "uzbek": "ko'z atrofidagi halqasimon mushak"},
                        {"latin": "M. corrugator supercilii", "uzbek": "qoshni tirishtiruvchi mushak"},
                        {"latin": "M. procerus", "uzbek": "burun usti mushagi, takabburlik mushagi"},
                        {"latin": "M. nasalis", "uzbek": "burun mushagi"},
                        {"latin": "M. levator labii superioris", "uzbek": "yuqori labni ko'taruvchi mushak"},
                        {"latin": "M. levator labii superioris alaeque nasi", "uzbek": "yuqori lab va burun qanotini ko'taruvchi mushak"},
                        {"latin": "M. zygomaticus major", "uzbek": "katta yonoq mushagi"},
                        {"latin": "M. zygomaticus minor", "uzbek": "kichik yonoq mushagi"},
                        {"latin": "M. risorius", "uzbek": "kulgich mushagi"},
                        {"latin": "M. buccinator", "uzbek": "lunj mushagi"},
                        {"latin": "M. orbicularis oris", "uzbek": "og'iz atrofidagi halqasimon mushak"},
                        {"latin": "M. depressor anguli oris", "uzbek": "og'iz burchagini tushiruvchi mushak"},
                        {"latin": "M. depressor labii inferioris", "uzbek": "pastki labni tushiruvchi mushak"},
                        {"latin": "M. mentalis", "uzbek": "iyak mushagi"},
                        {"latin": "Platysma", "uzbek": "bo'yinning teri osti mushagi, yuz mimikasida ham qatnashadi"},
                    ],
                },
            ],
        },
        {
            "title": "Bo'yin mushaklari",
            "sections": [
                {
                    "title": "Bo'yin mushaklari",
                    "image_url": None,
                    "entries": [
                        {"latin": "M. zygomaticus major", "uzbek": "katta yonoq mushagi"},
                        {"latin": "M. risorius", "uzbek": "kulgich mushagi"},
                        {"latin": "M. digastricus (venter anterior)", "uzbek": "ikki qorinchali mushakning oldingi qismi"},
                        {"latin": "M. digastricus (venter posterior)", "uzbek": "ikki qorinchali mushakning orqa qismi"},
                        {"latin": "M. mylohyoideus", "uzbek": "pastki jag'-tilosti mushagi"},
                        {"latin": "M. stylohyoideus", "uzbek": "bigizsimon-tilosti mushagi"},
                        {"latin": "M. masseter", "uzbek": "chaynov mushagi"},
                        {"latin": "M. sternohyoideus", "uzbek": "to'sh-tilosti mushagi"},
                        {"latin": "M. omohyoideus (venter superior)", "uzbek": "kurak-tilosti mushagi, yuqori qorin qismi"},
                        {"latin": "M. sternocleidomastoideus", "uzbek": "to'sh-o'mrov-so'rg'ichsimon mushak"},
                        {"latin": "M. trapezius", "uzbek": "trapetsiyasimon mushak"},
                        {"latin": "Platysma", "uzbek": "bo'yinning teri osti mushagi"},
                        {"latin": "M. cricothyroideus", "uzbek": "halqumsimon-qalqonsimon tog'ay mushagi"},
                    ],
                },
            ],
        },
    ]

    print("🌱 Seeding database...")

    for topic_data in data:
        topic = Topic(title=topic_data["title"])
        db.add(topic)
        db.flush()

        for section_data in topic_data.get("sections", []):
            section = Section(
                topic_uid=topic.uid,
                title=section_data["title"],
                image_url=section_data.get("image_url"),
            )
            db.add(section)
            db.flush()

            for entry_data in section_data.get("entries", []):
                db.add(Entry(
                    topic_uid=topic.uid,
                    section_uid=section.uid,
                    latin=entry_data["latin"],
                    uzbek=entry_data["uzbek"],
                ))

        for entry_data in topic_data.get("entries", []):
            db.add(Entry(
                topic_uid=topic.uid,
                latin=entry_data["latin"],
                uzbek=entry_data["uzbek"],
            ))

        print(f"  ✅ {topic_data['title']}")

    db.commit()
    db.close()
    print("✅ Seeding complete!")

if __name__ == "__main__":
    seed()